In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer

In [2]:
df = pd.read_csv('titanic_data_updated.csv')

df

     PassengerId Survived  Pclass  ...     Fare Cabin  Embarked
0              1       no   third  ...   7.2500   NaN         S
1              2      yes   first  ...  71.2833   C85         C
2              3      yes   third  ...   7.9250   NaN         S
3              4      yes   first  ...  53.1000  C123         S
4              5       no   third  ...   8.0500   NaN         S
..           ...      ...     ...  ...      ...   ...       ...
886          887       no  second  ...  13.0000   NaN         S
887          888      yes   first  ...  30.0000   B42         S
888          889       no   third  ...  23.4500   NaN         S
889          890      yes   first  ...  30.0000  C148         C
890          891       no   third  ...   7.7500   NaN         Q

[891 rows x 12 columns]

# Starter, Train Test and Handling Missing Values)

## 3.3 Feature Engineering Starter

In [3]:
df.drop(['PassengerId', 'Name', 'Ticket'], axis=1, inplace=True)

In [4]:
df

    Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0         no   third    male  22.0      1      0   7.2500   NaN        S
1        yes   first  female  38.0      1      0  71.2833   C85        C
2        yes   third  female  26.0      0      0   7.9250   NaN        S
3        yes   first  female  35.0      1      0  53.1000  C123        S
4         no   third    male  35.0      0      0   8.0500   NaN        S
..       ...     ...     ...   ...    ...    ...      ...   ...      ...
886       no  second    male  27.0      0      0  13.0000   NaN        S
887      yes   first  female  19.0      0      0  30.0000   B42        S
888       no   third  female   NaN      1      2  23.4500   NaN        S
889      yes   first    male  26.0      0      0  30.0000  C148        C
890       no   third    male  32.0      0      0   7.7500   NaN        Q

[891 rows x 9 columns]

In [6]:
df.isnull().sum()

df.drop(['Cabin'], axis=1, inplace=True)

df

    Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         no   third    male  22.0      1      0   7.2500        S
1        yes   first  female  38.0      1      0  71.2833        C
2        yes   third  female  26.0      0      0   7.9250        S
3        yes   first  female  35.0      1      0  53.1000        S
4         no   third    male  35.0      0      0   8.0500        S
..       ...     ...     ...   ...    ...    ...      ...      ...
886       no  second    male  27.0      0      0  13.0000        S
887      yes   first  female  19.0      0      0  30.0000        S
888       no   third  female   NaN      1      2  23.4500        S
889      yes   first    male  26.0      0      0  30.0000        C
890       no   third    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [8]:
x = df.drop(['Survived'], axis=1)

x

     Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0     third    male  22.0      1      0   7.2500        S
1     first  female  38.0      1      0  71.2833        C
2     third  female  26.0      0      0   7.9250        S
3     first  female  35.0      1      0  53.1000        S
4     third    male  35.0      0      0   8.0500        S
..      ...     ...   ...    ...    ...      ...      ...
886  second    male  27.0      0      0  13.0000        S
887   first  female  19.0      0      0  30.0000        S
888   third  female   NaN      1      2  23.4500        S
889   first    male  26.0      0      0  30.0000        C
890   third    male  32.0      0      0   7.7500        Q

[891 rows x 7 columns]

In [10]:
y = df['Survived']

y

0       no
1      yes
2      yes
3      yes
4       no
      ...
886     no
887    yes
888     no
889    yes
890     no
Name: Survived, Length: 891, dtype: object

In [11]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [14]:
x_train
display(y_train)

331     no
733     no
382     no
704     no
813     no
      ...
106    yes
270     no
860     no
435    yes
102     no
Name: Survived, Length: 712, dtype: object

In [ ]:
x_test