# 1. Diabetes Dataset – Missing Value Imputation & Encoding

In [52]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder

In [22]:
df = pd.read_csv("diabetes.csv")

df

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  DiabetesPedigreeFunction  Age  Outcome
0              6      148             72             35        0  33.6                     0.627   50        1
1              1       85             66             29        0  26.6                     0.351   31        0
2              8      183             64              0        0  23.3                     0.672   32        1
3              1       89             66             23       94  28.1                     0.167   21        0
4              0      137             40             35      168  43.1                     2.288   33        1
..           ...      ...            ...            ...      ...   ...                       ...  ...      ...
763           10      101             76             48      180  32.9                     0.171   63        0
764            2      122             70             27        0  36.8                     0.340   27        0
765            5      121             72             23      112  26.2                     0.245   30        0
766            1      126             60              0        0  30.1                     0.349   47        1
767            1       93             70             31        0  30.4                     0.315   23        0

[768 rows x 9 columns]

In [23]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [24]:
invalid_cols = ['Glucose', 'BloodPressure', 'BMI']

df[invalid_cols] = df[invalid_cols].replace(0, np.nan)

In [25]:
df.isnull().sum()

Pregnancies                  0
Glucose                      5
BloodPressure               35
SkinThickness                0
Insulin                      0
BMI                         11
DiabetesPedigreeFunction     0
Age                          0
Outcome                      0
dtype: int64

In [26]:
df['Glucose'] = df['Glucose'].fillna(df['Glucose'].median())
df['BloodPressure'] = df['BloodPressure'].fillna(df['BloodPressure'].median())
df['BMI'] = df['BMI'].fillna(df['BMI'].median())

In [27]:
df

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  DiabetesPedigreeFunction  Age  Outcome
0              6    148.0           72.0             35        0  33.6                     0.627   50        1
1              1     85.0           66.0             29        0  26.6                     0.351   31        0
2              8    183.0           64.0              0        0  23.3                     0.672   32        1
3              1     89.0           66.0             23       94  28.1                     0.167   21        0
4              0    137.0           40.0             35      168  43.1                     2.288   33        1
..           ...      ...            ...            ...      ...   ...                       ...  ...      ...
763           10    101.0           76.0             48      180  32.9                     0.171   63        0
764            2    122.0           70.0             27        0  36.8                     0.340   27        0
765            5    121.0           72.0             23      112  26.2                     0.245   30        0
766            1    126.0           60.0              0        0  30.1                     0.349   47        1
767            1     93.0           70.0             31        0  30.4                     0.315   23        0

[768 rows x 9 columns]

In [28]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [29]:
def age_group(age):
    if age < 30:
        return "Young"
    elif age <= 50:
        return "Adult"
    else:
        return "Senior"

df['Age_Group'] = df['Age'].apply(age_group)

In [30]:
df

     Pregnancies  Glucose  BloodPressure  SkinThickness  ...  DiabetesPedigreeFunction  Age  Outcome  Age_Group
0              6    148.0           72.0             35  ...                     0.627   50        1      Adult
1              1     85.0           66.0             29  ...                     0.351   31        0      Adult
2              8    183.0           64.0              0  ...                     0.672   32        1      Adult
3              1     89.0           66.0             23  ...                     0.167   21        0      Young
4              0    137.0           40.0             35  ...                     2.288   33        1      Adult
..           ...      ...            ...            ...  ...                       ...  ...      ...        ...
763           10    101.0           76.0             48  ...                     0.171   63        0     Senior
764            2    122.0           70.0             27  ...                     0.340   27        0      Young
765            5    121.0           72.0             23  ...                     0.245   30        0      Adult
766            1    126.0           60.0              0  ...                     0.349   47        1      Adult
767            1     93.0           70.0             31  ...                     0.315   23        0      Young

[768 rows x 10 columns]

In [31]:
mapping = {
    'Young': 0,
    'Adult': 1,
    'Senior': 2
}

df['Age_Group_Encoder'] = df['Age_Group'].map(mapping)

In [32]:
df

     Pregnancies  Glucose  BloodPressure  SkinThickness  ...  Age  Outcome  Age_Group  Age_Group_Encoder
0              6    148.0           72.0             35  ...   50        1      Adult                  1
1              1     85.0           66.0             29  ...   31        0      Adult                  1
2              8    183.0           64.0              0  ...   32        1      Adult                  1
3              1     89.0           66.0             23  ...   21        0      Young                  0
4              0    137.0           40.0             35  ...   33        1      Adult                  1
..           ...      ...            ...            ...  ...  ...      ...        ...                ...
763           10    101.0           76.0             48  ...   63        0     Senior                  2
764            2    122.0           70.0             27  ...   27        0      Young                  0
765            5    121.0           72.0             23  ...   30        0      Adult                  1
766            1    126.0           60.0              0  ...   47        1      Adult                  1
767            1     93.0           70.0             31  ...   23        0      Young                  0

[768 rows x 11 columns]

# 2. Heart Disease Dataset – One Hot Encoding

In [33]:
df = pd.read_csv("heart.csv")

df

      age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  ca  thal  target
0      52    1   0       125   212    0        1      168      0      1.0      2   2     3       0
1      53    1   0       140   203    1        0      155      1      3.1      0   0     3       0
2      70    1   0       145   174    0        1      125      1      2.6      0   0     3       0
3      61    1   0       148   203    0        1      161      0      0.0      2   1     3       0
4      62    0   0       138   294    1        1      106      0      1.9      1   3     2       0
...   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...    ...  ..   ...     ...
1020   59    1   1       140   221    0        1      164      1      0.0      2   0     2       1
1021   60    1   0       125   258    0        0      141      1      2.8      1   1     3       0
1022   47    1   0       110   275    0        0      118      1      1.0      1   1     2       0
1023   50    0   0       110   254    0        0      159      0      0.0      2   0     2       1
1024   54    1   0       120   188    0        1      113      0      1.4      1   1     3       0

[1025 rows x 14 columns]

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1025 non-null   int64
 1   sex       1025 non-null   int64
 2   cp        1025 non-null   int64
 3   trestbps  1025 non-null   int64
 4   chol      1025 non-null   int64
 5   fbs       1025 non-null   int64
 6   restecg   1025 non-null   int64
 7   thalach   1025 non-null   int64
 8   exang     1025 non-null   int64
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64
 11  ca        1025 non-null   int64
 12  thal      1025 non-null   int64
 13  target    1025 non-null   int64
dtypes: float64(1), int64(13)
memory usage: 112.2 KB

In [54]:
print("Before Encoding:", df.shape)

Before Encoding: (1025, 14)

In [55]:
cp_ohe = OneHotEncoder(sparse_output=False).set_output(transform='pandas')

cp_ohe.fit(df[['cp']])

OneHotEncoder(sparse_output=False)

In [56]:
encoder_df = cp_ohe.transform(df[['cp']])
df = pd.concat([df, encoder_df], axis=1)

In [57]:
df

      age  sex  cp  trestbps  chol  fbs  restecg  thalach  ...  slope  ca  thal  target  cp_0  cp_1  cp_2  cp_3
0      52    1   0       125   212    0        1      168  ...      2   2     3       0   1.0   0.0   0.0   0.0
1      53    1   0       140   203    1        0      155  ...      0   0     3       0   1.0   0.0   0.0   0.0
2      70    1   0       145   174    0        1      125  ...      0   0     3       0   1.0   0.0   0.0   0.0
3      61    1   0       148   203    0        1      161  ...      2   1     3       0   1.0   0.0   0.0   0.0
4      62    0   0       138   294    1        1      106  ...      1   3     2       0   1.0   0.0   0.0   0.0
...   ...  ...  ..       ...   ...  ...      ...      ...  ...    ...  ..   ...     ...   ...   ...   ...   ...
1020   59    1   1       140   221    0        1      164  ...      2   0     2       1   0.0   1.0   0.0   0.0
1021   60    1   0       125   258    0        0      141  ...      1   1     3       0   1.0   0.0   0.0   0.0
1022   47    1   0       110   275    0        0      118  ...      1   1     2       0   1.0   0.0   0.0   0.0
1023   50    0   0       110   254    0        0      159  ...      2   0     2       1   1.0   0.0   0.0   0.0
1024   54    1   0       120   188    0        1      113  ...      1   1     3       0   1.0   0.0   0.0   0.0

[1025 rows x 18 columns]

In [58]:
thal_ohe = OneHotEncoder(sparse_output=False).set_output(transform='pandas')
thal_ohe.fit(df[['thal']])

thal_encoder = thal_ohe.transform(df[['thal']])
df = pd.concat([df, thal_encoder], axis=1)

In [59]:
df

      age  sex  cp  trestbps  chol  fbs  restecg  thalach  ...  cp_0  cp_1  cp_2  cp_3  thal_0  thal_1  thal_2  thal_3
0      52    1   0       125   212    0        1      168  ...   1.0   0.0   0.0   0.0     0.0     0.0     0.0     1.0
1      53    1   0       140   203    1        0      155  ...   1.0   0.0   0.0   0.0     0.0     0.0     0.0     1.0
2      70    1   0       145   174    0        1      125  ...   1.0   0.0   0.0   0.0     0.0     0.0     0.0     1.0
3      61    1   0       148   203    0        1      161  ...   1.0   0.0   0.0   0.0     0.0     0.0     0.0     1.0
4      62    0   0       138   294    1        1      106  ...   1.0   0.0   0.0   0.0     0.0     0.0     1.0     0.0
...   ...  ...  ..       ...   ...  ...      ...      ...  ...   ...   ...   ...   ...     ...     ...     ...     ...
1020   59    1   1       140   221    0        1      164  ...   0.0   1.0   0.0   0.0     0.0     0.0     1.0     0.0
1021   60    1   0       125   258    0        0      141  ...   1.0   0.0   0.0   0.0     0.0     0.0     0.0     1.0
1022   47    1   0       110   275    0        0      118  ...   1.0   0.0   0.0   0.0     0.0     0.0     1.0     0.0
1023   50    0   0       110   254    0        0      159  ...   1.0   0.0   0.0   0.0     0.0     0.0     1.0     0.0
1024   54    1   0       120   188    0        1      113  ...   1.0   0.0   0.0   0.0     0.0     0.0     0.0     1.0

[1025 rows x 22 columns]

In [60]:
df.drop(['cp', 'thal'], axis=1)

      age  sex  trestbps  chol  fbs  restecg  thalach  exang  ...  cp_0  cp_1  cp_2  cp_3  thal_0  thal_1  thal_2  thal_3
0      52    1       125   212    0        1      168      0  ...   1.0   0.0   0.0   0.0     0.0     0.0     0.0     1.0
1      53    1       140   203    1        0      155      1  ...   1.0   0.0   0.0   0.0     0.0     0.0     0.0     1.0
2      70    1       145   174    0        1      125      1  ...   1.0   0.0   0.0   0.0     0.0     0.0     0.0     1.0
3      61    1       148   203    0        1      161      0  ...   1.0   0.0   0.0   0.0     0.0     0.0     0.0     1.0
4      62    0       138   294    1        1      106      0  ...   1.0   0.0   0.0   0.0     0.0     0.0     1.0     0.0
...   ...  ...       ...   ...  ...      ...      ...    ...  ...   ...   ...   ...   ...     ...     ...     ...     ...
1020   59    1       140   221    0        1      164      1  ...   0.0   1.0   0.0   0.0     0.0     0.0     1.0     0.0
1021   60    1       125   258    0        0      141      1  ...   1.0   0.0   0.0   0.0     0.0     0.0     0.0     1.0
1022   47    1       110   275    0        0      118      1  ...   1.0   0.0   0.0   0.0     0.0     0.0     1.0     0.0
1023   50    0       110   254    0        0      159      0  ...   1.0   0.0   0.0   0.0     0.0     0.0     1.0     0.0
1024   54    1       120   188    0        1      113      0  ...   1.0   0.0   0.0   0.0     0.0     0.0     0.0     1.0

[1025 rows x 20 columns]