In [1]:
import pandas as pd
import numpy as np

In [3]:
# numpy array

arr = np.array([[1, 2], [3, 4]])
arr

array([[1, 2],
       [3, 4]])

In [5]:
df = pd.DataFrame(arr, columns=["A", "B"])
df

   A  B
0  1  2
1  3  4

# Series

In [6]:
s = pd.Series([10, 20, 30], index=["a", "b", "c"])
s

a    10
b    20
c    30
dtype: int64

In [7]:
s['a']

np.int64(10)

# Problem:

In [11]:
for indx in s.index:
    s[indx] = s[indx] + 10
s

a    40
b    50
c    60
dtype: int64

In [12]:
s = s+10
s

a    50
b    60
c    70
dtype: int64

In [13]:
df = pd.DataFrame(
    {
        "Name" : ["A", "B"],
        "Age" : [20, 21]
    }
)

df

  Name  Age
0    A   20
1    B   21

In [15]:
print(type(df["Name"]))

<class 'pandas.core.series.Series'>

In [16]:
print("Index ",df.index)

Index  RangeIndex(start=0, stop=2, step=1)

In [19]:
df1 = pd.Series([1, 2], index=["a", "b"])
df2 = pd.Series([3, 4], index=["b", "a"])

print(df1 + df2)

a    5
b    5
dtype: int64

In [51]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("spscientist/students-performance-in-exams")

print("Path to dataset files:", path)

Path to dataset files: C:\Users\Tuhin Ahmed\.cache\kagglehub\datasets\spscientist\students-performance-in-exams\versions\1

In [52]:
path = r"C:\Users\Tuhin Ahmed\.cache\kagglehub\datasets\spscientist\students-performance-in-exams\versions\1\StudentsPerformance.csv"

df = pd.read_csv(path)

In [53]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [22]:
df = pd.DataFrame(
    {
        "Name" : ["A", "B"],
        "Age" : [20, 21]
    },
    index = ["x", "y"]
)

df

  Name  Age
x    A   20
y    B   21

In [24]:
df["Name"]

x    A
y    B
Name: Name, dtype: object

In [25]:
df["Age"]

x    20
y    21
Name: Age, dtype: int64

In [26]:
df.iloc[0]

Name     A
Age     20
Name: x, dtype: object

In [27]:
df.iloc[0:2]

  Name  Age
x    A   20
y    B   21

In [28]:
# get specific cell
df.iloc[0,0]

'A'

In [29]:
for i in range(len(df)):
    print(df.iloc[i])

Name     A
Age     20
Name: x, dtype: object
Name     B
Age     21
Name: y, dtype: object

In [31]:
# get multiple rows

df.loc[["x","y"]]

  Name  Age
x    A   20
y    B   21

In [33]:
df.loc["y", "Age"]

np.int64(21)

In [34]:
# Conditional filtering

df.loc[df ["Age"] > 18]

  Name  Age
x    A   20
y    B   21

# Data Manipulation

In [37]:
df = pd.DataFrame(
    {
        "Name" : ["A", "B"],
        "Age" : [20, 21]
    }
)

df

# add new columns
df["Marks"] = [80, 90]

df

  Name  Age  Marks
0    A   20     80
1    B   21     90

In [40]:
# drop columns

df2 = df.drop("Marks", axis=1)
df2

  Name  Age
0    A   20
1    B   21

In [43]:
# Filtering

df = pd.DataFrame(
    {
        "Name" : ["A", "B", "C"],
        "Age" : [18, 21, 25]
    }
)

df

  Name  Age
0    A   18
1    B   21
2    C   25

In [44]:
filtered_df = df[df["Age"]> 18]
filtered_df

  Name  Age
1    B   21
2    C   25

# Sorting

In [45]:
df = pd.DataFrame(
    {
        "Name" : ["A", "B", "C"],
        "Age" : [25, 21, 18]
    }
)

df

  Name  Age
0    A   25
1    B   21
2    C   18

In [46]:
# age

sorted_df = df.sort_values(by = "Age")
sorted_df

  Name  Age
2    C   18
1    B   21
0    A   25

# Iteration

In [49]:
for index, row in df.iterrows():
    print(row["Name"], row["Age"])

A 25
B 21
C 18

# vectorization

In [50]:
df = pd.DataFrame({
    "Marks" : [50, 60, 70]
})
df

   Marks
0     50
1     60
2     70

# Mini Project

In [57]:
data = {
    "Name" : ["Alice", "Bob", "Charlie", "David", "Eva"],
    "Age" : [20, 25, 23, 26, 29],
    "Marks" : [85, 67, 90, 45, 88]
}

df = pd.DataFrame(data)
df

      Name  Age  Marks
0    Alice   20     85
1      Bob   25     67
2  Charlie   23     90
3    David   26     45
4      Eva   29     88

In [59]:
# add a grade columns

def assign_grade(marks):
    if marks >= 80:
        return "A"
    elif marks >= 60:
        return "B"
    else:
        return "C"

df["Grade"] = df["Marks"].apply(assign_grade)

In [60]:
df

      Name  Age  Marks Grade
0    Alice   20     85     A
1      Bob   25     67     B
2  Charlie   23     90     A
3    David   26     45     C
4      Eva   29     88     A

In [63]:
# Filter Student

top_students = df[df["Marks"]>80]
top_students

      Name  Age  Marks Grade
0    Alice   20     85     A
2  Charlie   23     90     A
4      Eva   29     88     A

In [65]:
# sort student

sorted_df = df.sort_values(by="Marks", ascending=True)
sorted_df

      Name  Age  Marks Grade
3    David   26     45     C
1      Bob   25     67     B
0    Alice   20     85     A
4      Eva   29     88     A
2  Charlie   23     90     A

In [66]:
# average marks

avg_marks = df["Marks"].mean()
avg_marks

np.float64(75.0)

In [67]:
# save as a csv file

df.to_csv("Student_output.csv", index=False)

In [68]:
# Advance