In [ ]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder, LabelEncoder, StandardScaler, MinMaxScaler
from sklearn.metrics import accuracy_score, precision_score, recall_score, classification_report

In [ ]:
df = pd.read_csv("finnova_train.csv")
df.head()

,Txn_ID,Feature_1,Feature_2,Feature_3,Feature_4,Feature_5,Feature_6,Feature_7,Feature_8,Feature_9,...,Feature_21,Feature_22,Feature_23,Feature_24,Feature_25,Feature_26,Feature_27,Feature_28,Txn_Value,Risk_Flag
0,TXN173209,-2.183585,1.892761,-1.142737,-2.436105,1.396925,3.717930,-2.123038,-1.543484,-0.481181,...,-0.564747,-0.400373,0.350173,0.993206,-0.139172,0.736772,0.113477,0.148835,0.61,0.0
1,TXN159667,-1.546892,1.850485,2.176940,3.035659,-1.192864,0.955754,-1.758738,-1.797986,-0.829465,...,-1.286355,0.351282,0.008838,0.320438,-0.074777,0.232331,0.071991,0.134451,0.00,0.0
2,TXN157896,-1.522655,1.081601,0.182110,0.990186,1.586729,4.474267,-0.949357,1.709973,-0.447918,...,-0.012369,-0.211502,0.074203,0.986499,0.014727,-0.134744,-0.839414,-0.318542,37.05,0.0
3,TXN103239,-0.664094,0.425969,2.691272,-1.700911,-0.376081,-0.673883,0.437586,-0.247356,2.562786,...,-0.150361,0.098032,-0.369068,0.336507,0.471566,-0.840827,-0.092741,-0.154443,14.53,0.0
4,TXN111043,-0.618800,0.601447,1.676447,-0.858323,-0.204625,-0.458810,0.958814,-0.406579,-1.380236,...,-0.397481,-0.593460,0.038502,0.321442,-0.458293,-0.860966,-0.238523,-0.083199,65.27,0.0

In [ ]:
df.shape

(61835, 31)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61835 entries, 0 to 61834
Data columns (total 31 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Txn_ID      61835 non-null  object
 1   Feature_1   61835 non-null  float64
 2   Feature_2   61835 non-null  float64
 3   Feature_3   61835 non-null  float64
 4   Feature_4   61835 non-null  float64
 5   Feature_5   61835 non-null  float64
 6   Feature_6   61835 non-null  float64
 7   Feature_7   61835 non-null  float64
 8   Feature_8   61835 non-null  float64
 9   Feature_9   61835 non-null  float64
 10  Feature_10  61835 non-null  float64
 11  Feature_11  61835 non-null  float64
 12  Feature_12  61835 non-null  float64
 13  Feature_13  61835 non-null  float64
 14  Feature_14  61835 non-null  float64
 15  Feature_15  61835 non-null  float64
 16  Feature_16  61835 non-null  float64
 17  Feature_17  61835 non-null  float64
 18  Feature_18  61835 non-null  float64
 19  Feature_19  61835 non-null  float64
 20  Feature_20  61835 non-null  float64
 21  Feature_21  61835 non-null  float64
 22  Feature_22  61835 non-null  float64
 23  Feature_23  61835 non-null  float64
 24  Feature_24  61835 non-null  float64
 25  Feature_25  61835 non-null  float64
 26  Feature_26  61835 non-null  float64
 27  Feature_27  61835 non-null  float64
 28  Feature_28  61835 non-null  float64
 29  Txn_Value   61835 non-null  float64
 30  Risk_Flag   61835 non-null  float64
dtypes: float64(30), object(1)
memory usage: 14.6+ MB

In [ ]:
df.describe()

,Feature_1,Feature_2,Feature_3,Feature_4,Feature_5,Feature_6,Feature_7,Feature_8,Feature_9,Feature_10,...,Feature_21,Feature_22,Feature_23,Feature_24,Feature_25,Feature_26,Feature_27,Feature_28,Txn_Value,Risk_Flag
count,61835.000000,61835.000000,61835.000000,61835.000000,61835.000000,61835.000000,61835.000000,61835.000000,61835.000000,61835.000000,...,61835.000000,61835.000000,61835.000000,61835.000000,61835.000000,61835.000000,61835.000000,61835.000000,61835.000000,61835.000000
mean,-0.244851,0.002595,0.673513,0.147324,-0.284318,0.088468,-0.118156,0.055544,-0.078844,-0.013626,...,-0.034308,-0.114971,-0.035472,0.012155,0.132425,0.027692,0.000045,0.002627,119.256456,0.002054
std,1.821858,1.605185,1.265471,1.334578,1.312770,1.288695,1.168961,1.231941,1.100590,1.061106,...,0.742876,0.639684,0.614763,0.595978,0.437992,0.492318,0.402403,0.339263,320.911204,0.045273
min,-56.398700,-72.712819,-30.004305,-5.178794,-42.154270,-26.159992,-26.551313,-41.476563,-8.750670,-18.269044,...,-20.265981,-10.922314,-44.810181,-2.818038,-10.292297,-2.528426,-22.567251,-11.715905,0.000000,0.000000
25%,-1.022168,-0.577859,0.174882,-0.712233,-0.901891,-0.655907,-0.605469,-0.135710,-0.705782,-0.484522,...,-0.225656,-0.543088,-0.173972,-0.323098,-0.133123,-0.323799,-0.060247,-0.004765,8.630000,0.000000
50%,-0.253322,0.091309,0.747249,0.174666,-0.318627,-0.164758,-0.068879,0.077122,-0.140325,-0.091747,...,-0.058131,-0.091395,-0.046952,0.069939,0.168992,-0.062326,0.010972,0.023397,31.720000,0.000000
75%,1.157522,0.757751,1.365011,1.009898,0.237849,0.473173,0.407868,0.369531,0.506828,0.435884,...,0.117019,0.307439,0.081821,0.408770,0.419114,0.293790,0.084810,0.076378,106.990000,0.000000
max,1.691123,16.167472,9.382670,16.707839,34.810966,22.516958,36.681752,19.165535,15.596274,23.743331,...,27.205065,5.807653,18.998727,4.021440,5.376410,3.465049,11.134791,33.842626,25361.210000,1.000000

In [ ]:
df.isnull().sum()

Txn_ID        0
Feature_1     0
Feature_2     0
Feature_3     0
Feature_4     0
Feature_5     0
Feature_6     0
Feature_7     0
Feature_8     0
Feature_9     0
Feature_10    0
Feature_11    0
Feature_12    0
Feature_13    0
Feature_14    0
Feature_15    0
Feature_16    0
Feature_17    0
Feature_18    0
Feature_19    0
Feature_20    0
Feature_21    0
Feature_22    0
Feature_23    0
Feature_24    0
Feature_25    0
Feature_26    0
Feature_27    0
Feature_28    0
Txn_Value     0
Risk_Flag     0
dtype: int64

In [ ]:
# Check for duplicate rows in the dataset
print(f"Inital Duplicate count: {df.duplicated().sum()}")

# Remove duplicate rows to ensure data quality
df.drop_duplicates(inplace=True)

# Verify that duplicates have been removed
print(f"Duplicate count after removal: {df.duplicated().sum()}")

Inital Duplicate count: 0
Duplicate count after removal: 0

In [ ]:
# scaler = StandardScaler()

# X_train = scaler.fit_transform(X_train)
# X_test = scaler.fit(X_test)

In [ ]:
X = df.drop(['Txn_ID', 'Risk_Flag'], axis=1)
y = df['Risk_Flag']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [ ]:
# numerical columns
numerical = X_train.select_dtypes(
    include=["int64", "float64"]
).columns

numerical

Index(['Feature_1', 'Feature_2', 'Feature_3', 'Feature_4', 'Feature_5',
       'Feature_6', 'Feature_7', 'Feature_8', 'Feature_9', 'Feature_10',
       'Feature_11', 'Feature_12', 'Feature_13', 'Feature_14', 'Feature_15',
       'Feature_16', 'Feature_17', 'Feature_18', 'Feature_19', 'Feature_20',
       'Feature_21', 'Feature_22', 'Feature_23', 'Feature_24', 'Feature_25',
       'Feature_26', 'Feature_27', 'Feature_28', 'Txn_Value'],
      dtype='object')

In [ ]:
numerical_transformers = Pipeline(
    steps=[
        ('scaler', StandardScaler())
    ]
)

numerical_transformers

Pipeline(steps=[('scaler', StandardScaler())])

In [ ]:
preprocessor = ColumnTransformer(
    transformers=[
        ('numerical', numerical_transformers, numerical)
    ],
    remainder="passthrough"
)

## Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
lr_pipe = Pipeline(
    steps=[
        ('preprocessor', preprocessor),
        ('model', LogisticRegression())
    ]
)

lr_pipe.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('numerical',
                                                  Pipeline(steps=[('scaler',
                                                                   StandardScaler())]),
                                                  Index(['Feature_1', 'Feature_2', 'Feature_3', 'Feature_4', 'Feature_5',
       'Feature_6', 'Feature_7', 'Feature_8', 'Feature_9', 'Feature_10',
       'Feature_11', 'Feature_12', 'Feature_13', 'Feature_14', 'Feature_15',
       'Feature_16', 'Feature_17', 'Feature_18', 'Feature_19', 'Feature_20',
       'Feature_21', 'Feature_22', 'Feature_23', 'Feature_24', 'Feature_25',
       'Feature_26', 'Feature_27', 'Feature_28', 'Txn_Value'],
      dtype='object'))])),
                ('model', LogisticRegression())])

In [ ]:
y_pred = lr_pipe.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.9987062343333064

In [ ]:
# Logistic Regression

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00     12342
         1.0       0.76      0.52      0.62        25

    accuracy                           1.00     12367
   macro avg       0.88      0.76      0.81     12367
weighted avg       1.00      1.00      1.00     12367

In [ ]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
print(cm)

[[12338     4]
 [   12    13]]

In [ ]:
from sklearn.linear_model import LogisticRegression

lr_pipe = Pipeline([
    ('preprocessor', preprocessor),
    ('model', LogisticRegression(class_weight='balanced'))
])

lr_pipe.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('numerical',
                                                  Pipeline(steps=[('scaler',
                                                                   StandardScaler())]),
                                                  Index(['Feature_1', 'Feature_2', 'Feature_3', 'Feature_4', 'Feature_5',
       'Feature_6', 'Feature_7', 'Feature_8', 'Feature_9', 'Feature_10',
       'Feature_11', 'Feature_12', 'Feature_13', 'Feature_14', 'Feature_15',
       'Feature_16', 'Feature_17', 'Feature_18', 'Feature_19', 'Feature_20',
       'Feature_21', 'Feature_22', 'Feature_23', 'Feature_24', 'Feature_25',
       'Feature_26', 'Feature_27', 'Feature_28', 'Txn_Value'],
      dtype='object'))])),
                ('model', LogisticRegression(class_weight='balanced'))])

In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00     12342
         1.0       0.76      0.52      0.62        25

    accuracy                           1.00     12367
   macro avg       0.88      0.76      0.81     12367
weighted avg       1.00      1.00      1.00     12367

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
# Random Forest Classifier

rf_pipe = Pipeline(
    steps=[
        ('preprocessor', preprocessor),
        ('model', RandomForestClassifier(
            n_estimators=100,
            random_state=42
        ))
    ]
)

In [ ]:
rf_pipe.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('numerical',
                                                  Pipeline(steps=[('scaler',
                                                                   StandardScaler())]),
                                                  Index(['Feature_1', 'Feature_2', 'Feature_3', 'Feature_4', 'Feature_5',
       'Feature_6', 'Feature_7', 'Feature_8', 'Feature_9', 'Feature_10',
       'Feature_11', 'Feature_12', 'Feature_13', 'Feature_14', 'Feature_15',
       'Feature_16', 'Feature_17', 'Feature_18', 'Feature_19', 'Feature_20',
       'Feature_21', 'Feature_22', 'Feature_23', 'Feature_24', 'Feature_25',
       'Feature_26', 'Feature_27', 'Feature_28', 'Txn_Value'],
      dtype='object'))])),
                ('model', RandomForestClassifier(random_state=42))])

In [ ]:
y_pred = rf_pipe.predict(X_test)

In [ ]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.9993531171666532

In [ ]:
# Random Forest Classifier

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00     12342
         1.0       0.90      0.76      0.83        25

    accuracy                           1.00     12367
   macro avg       0.95      0.88      0.91     12367
weighted avg       1.00      1.00      1.00     12367

In [ ]:
prediction = rf_pipe.predict(df)

submission = pd.DataFrame({
    "Txn_ID": df["Txn_ID"],
    "Risk_Flag": prediction
})

submission.to_csv("submission.csv", index=False)